module.exports = {
    acceptCookiesButton: '[data-testid=accept-button]',
    searchField: '#suggestion-search',
    searchResultArea: '[data-testid=search-result--const]',
    profileHeader: '[data-testid=hero__primary-text]',
    upcomingAccordionActor: '#actor-upcoming-projects',
    upcomingProjectsArea: '#accordion-item-actor-upcoming-projects',
    projectElements: '.ipc-metadata-list-summary-item__c',
    movieStatus: '[data-testid=tm-box-up]',
    openMenuButton: '#imdbHeader-navDrawerOpen',
    expandMenuItems: '[data-testid=category-expando]',
    innerMenuItems: '.ipc-list-item__text',
    listElements: '.ipc-metadata-list-summary-item__c',
    listElementsHeaders: '.ipc-metadata-list-summary-item__c h3',
    listElementsContent: '.ipc-html-content-inner-div',
    listElementsContentLinks: '.ipc-html-content-inner-div a',
    ratingButton: '[data-testid=hero-rating-bar__user-rating__unrated]',
    ratingModal: '[data-testid=promptable__pc]',
    rate5Star: '[aria-label="Rate 5"]',
    ratingModalButtons: '[data-testid=promptable__pc] button',
    signinOptions: '#signin-options',
    photosTitle: '[data-testid=photos-title] h3',
    photosGalleryButton: '[data-testid=mv-gallery-button]',
    openFilterButton: '.ipc-chip-dropdown',
    filtersArea: '.ipc-promptable-base__content',
    personFilterArea: '[data-testid=image-names-filter-container-test-id]',
    morePeopleDropdown: '[data-testid=select-dropdown-test-id]',
    mediaViewer: '[data-testid=media-viewer]',
    filteredImages: '[data-testid=sub-section-images] img',
    filterChips: '.ipc-chip__text',
    closeFiltersButton: '[data-testid=promptable__x]',
    header: 'h1',
    birthdayAccordion: '[data-testid=accordion-item-birthdayAccordion]',
    birthdayInputField: '[data-testid=birthday-input-test-id]',
    seeResultsButton: '[data-testid=adv-search-get-results]',
    birthDateAccordion: '#birthDateAccordion',
    birthDateStartField: '[data-testid=birthDate-start]',
    birthDateEndField: '[data-testid=birthDate-end]',
    birthDateFilterChip: '[data-testid="selected-input-chip-list-birthDate-Birth date"]'
}